### ISSUE TITLE
有什么必须设置的地方吗？

### ISSUE THREAD

**Issue by EdifierCN** [MarxJiao/vue-iscroll-directive#10]
main.js import 进来，使用Vue.use(VIscroll,{params})，在子组件的列表项加上加上v-iscroll，在检查器中可以看到包裹层已经被iscoll加上了style，但是滑上下拉没效果

**Comment by MarxJiao** [comment]
包裹层有设置高度吗

**Comment by EdifierCN** [comment]
![o 05i8xcd0cmn l6n ju7g](https://user-images.githubusercontent.com/22008960/29707835-43bb9a44-89b9-11e7-9725-8961000c0369.png)
![m_ji h9c qbgq8 tae1a3q](https://user-images.githubusercontent.com/22008960/29707841-498a952e-89b9-11e7-98c9-a8b7239d13bd.png)
外层的几个DIV都加了一遍高度，貌似不是这问题，有demo吗？

**Comment by MarxJiao** [comment]
参考下这个吧 https://github.com/MarxJiao/viscroll-demo

**Comment by EdifierCN** [comment]
谢谢！已经在关闭的问题中找到了demo，貌似是我标签写错现在不知道改了哪里正常了
