### ISSUE TITLE
这是 vue1 的版本吗？我这边报错

### ISSUE THREAD

**Issue by evolutionjay** [MarxJiao/vue-iscroll-directive#5]
已经安装了 iscroll@latest
vue2

按照readme 一样的方法

<img width="1280" alt="2017-04-21 11 57 14" src="https://cloud.githubusercontent.com/assets/4468540/25262317/d56ac08e-2689-11e7-8219-88ada4b22053.png">

**Comment by MarxJiao** [comment]
vue2 版本的。
有使用Vue.use()吗？

**Comment by evolutionjay** [comment]
有用use,等我回家尝试用codepen重现一下

**Comment by MarxJiao** [comment]
这是我做的一个简单的示例：http://marxjiao.com/viscroll-demo/     
代码在：https://github.com/MarxJiao/viscroll-demo
